Build against Eclipse 2024-06/JavaSE-17 by default
2024-09 builds with JavaSE-21, which breaks backward compatiblity with
older versions of Java (java.lang.NoClassDefFoundError:
java/util/SequencedCollection)

Signed-off-by: Dennis Wagelaar <dwagelaar@gmail.com>